---
- name: Configure Vault
  hosts: vault-1
  become: yes
  tasks:
     - name: Install Yum Utils
       yum:
         name: yum-utils
         state: present
     - name: Add HashiCorp Repo
       command: "sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"
     - name: Install Vault
       yum:
         name: vault
         state: present
