---
- name: Installing general dependencies via yum
  ansible.builtin.yum:
    name:
      - unzip
      - wget
      - tree
      - mlocate
      - curl
      - nmap-ncat
      - jq
      - epel-release
      - htop
      - ack
    state: present
    update_cache: true
  when: ansible_pkg_mgr == 'yum'

- name: Installing general dependencies via apt
  ansible.builtin.apt:
    name:
      - ack
      - acl
      - unzip
      - curl
      - software-properties-common
      - gnupg
      - wget
      - tree
      - mlocate
      - netcat
      - jq
      - htop
      - python-apt
    state: present
    update_cache: true
  when: ansible_pkg_mgr == 'apt'

- name: Installing Vault dependencies via dnf
  ansible.builtin.dnf:
    name:
      - unzip
      - wget
      - tree
      - mlocate
      - curl
      - nmap-ncat
      - jq
      - epel-release
    state: present
    update_cache: true
  when: ansible_pkg_mgr == 'dnf'

- name: Creating general group
  ansible.builtin.group:
    name: '{{ general_group }}'
    system: true
  when: general_create_account

- name: Creating general app user
  ansible.builtin.user:
    name: '{{ general_user }}'
    home: '{{ general_home_directory }}'
    group: '{{ general_group }}'
    shell: /sbin/nologin
    system: true
  when: general_create_account

- name: Creating Application directories
  ansible.builtin.file:
    state: directory
    recurse: true
    path: '{{ item }}'
    owner: '{{ general_user }}'
    group: '{{ general_group }}'
    mode: '0774'
  with_items:
    - '{{ application_directory }}'

- name: Create '/app/web' directory
  ansible.builtin.file:
    state: directory
    path: '{{ node_directory }}'

- name: Create '/app/mysql' directory
  ansible.builtin.file:
    state: directory
    path: '{{ mysql_data_directory }}'

- name: Create '/app/api' directory
  ansible.builtin.file:
    state: directory
    path: '{{ golang_api_directory }}'

- name: Setting client environment variables
  copy:
    content: |
      alias ll='ls -lah'
    dest: "/etc/profile.d/99-general.sh"
    mode: 0644

- name: Add Golang repository into sources list
  ansible.builtin.apt_repository:
    repo: deb http://ftp.de.debian.org/debian buster-backports main
    state: present

- name: Installing Golang dependencies via apt
  ansible.builtin.apt:
    name:
      - golang-1.15
      - golang-1.15-doc
      - golang-1.15-go
    state: present
    update_cache: true
  when: ansible_pkg_mgr == 'apt'

- name: Create a symbolic link for Golang
  ansible.builtin.file:
    src: /usr/lib/go-1.15/bin/go
    dest: /usr/bin/go
    owner: root
    group: root
    state: link