---
- name: JSON Handling
  hosts: deb-vault-1
  tasks:
     - name: Grab Json
       shell:
         "cat /home/akalaj/example.json"
       register: example
       tags: example
     - debug: msg="{{example.stdout}}"