- name: Add Debian Kernel repository into sources list
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main
    state: present

- name: Update to latest Kernel under buster-backports
  apt:
    upgrade: yes
    default_release: buster-backports
    update_cache: yes

- name: Remove 4.19 Kernel traces
  apt:
    pkg: linux-image-4.19*
    state: absent

- name: Reboot box if kernel/libs updated and requested by the system
  shell: sleep 10 && /sbin/shutdown -r now 'Rebooting box to update system libs/kernel as needed' 
  args:
      removes: /var/run/reboot-required
  async: 300
  poll: 0
  ignore_errors: true

- name: Wait for system to become reachable again
  wait_for_connection:
      delay: 60
      timeout: 300

- name: Verify new update (optional)
  command: uname -r
  register: uname_result

- name: Display new kernel version
  debug:
      var: uname_result.stdout_lines
