---
- name: Installing Nginx dependencies via dnf
  ansible.builtin.dnf:
    name:
      - nginx
    state: present
    update_cache: true
  when: ansible_pkg_mgr == 'dnf'

- name: Installing Nginx dependencies via apt
  ansible.builtin.apt:
    name:
      - nginx
    state: present
    update_cache: true
  when: ansible_pkg_mgr == 'apt'

- name: delete default nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: copy nginx site.conf
  template:
    src: sites-enabled.conf.j2
    dest: /etc/nginx/sites-enabled/default
    owner: root
    group: root
    mode: '0644'

- name: Restart service httpd, in all cases
  ansible.builtin.service:
    name: nginx
    state: restarted